import { PluginGeneratedSdk, PluginSdkActionConfig } from '../../types';

export class PluginSdkEngine {
  /**
   * Generates production-ready TypeScript SDK and Bubble Plugin Action code
   */
  public static generatePluginSdk(config: PluginSdkActionConfig): PluginGeneratedSdk {
    const actionNameClean = config.actionName.replace(/[^a-zA-Z0-9_]/g, '');
    
    // 1. Generate TypeScript Interfaces
    let tsInterfaces = `/**
 * TypeScript Type Definitions for Bubble Plugin Action: ${config.actionName}
 * Auto-generated by Bubble.io Dev Studio
 */

export interface ${actionNameClean}Properties {\n`;

    for (const p of config.parameters) {
      const tsType = p.type === 'number' ? 'number' : p.type === 'boolean' ? 'boolean' : p.type.startsWith('list_') ? 'string[]' : p.type === 'object' ? 'Record<string, any>' : 'string';
      const optional = p.required ? '' : '?';
      tsInterfaces += `  /** ${p.description || p.name} */\n  ${p.name}${optional}: ${tsType};\n`;
    }
    tsInterfaces += `}\n\n`;

    if (config.returnsValue && config.returnFields) {
      tsInterfaces += `export interface ${actionNameClean}Response {\n`;
      for (const rf of config.returnFields) {
        const tsType = rf.type === 'number' ? 'number' : rf.type === 'boolean' ? 'boolean' : 'string';
        tsInterfaces += `  ${rf.name}: ${tsType};\n`;
      }
      tsInterfaces += `}\n`;
    }

    // 2. Generate Server-Side Action Code (SSA)
    let ssaCode = `/**
 * Bubble Plugin Server-Side Action (SSA)
 * Action: ${config.actionName}
 * Paste into Bubble Plugin Editor > Actions > ${config.actionName} > Server-side execution
 */

async function(properties, context) {
  try {
    // Validate required parameters
`;

    for (const p of config.parameters.filter(p => p.required)) {
      ssaCode += `    if (!properties.${p.name}) {\n      throw new Error("Missing required field: '${p.name}'");\n    }\n`;
    }

    ssaCode += `\n    // Prepared Payload\n    const payload = {\n`;
    for (const p of config.parameters) {
      ssaCode += `      ${p.name}: properties.${p.name},\n`;
    }
    ssaCode += `    };\n\n`;

    if (config.apiUrl) {
      ssaCode += `    // External API Request via context.request or standard fetch\n`;
      ssaCode += `    const response = await fetch("${config.apiUrl}", {\n`;
      ssaCode += `      method: "${config.httpMethod || 'POST'}",\n`;
      ssaCode += `      headers: {\n`;
      ssaCode += `        "Content-Type": "application/json",\n`;
      if (config.headers) {
        for (const [hk, hv] of Object.entries(config.headers)) {
          ssaCode += `        "${hk}": "${hv}",\n`;
        }
      }
      ssaCode += `      },\n`;
      ssaCode += `      body: JSON.stringify(payload)\n`;
      ssaCode += `    });\n\n`;
      ssaCode += `    if (!response.ok) {\n      const errText = await response.text();\n      throw new Error(\`API error (\${response.status}): \${errText}\`);\n    }\n\n`;
      ssaCode += `    const data = await response.json();\n\n`;
    } else {
      ssaCode += `    // Process business logic\n    const data = { status: "success", executedAt: new Date().toISOString() };\n\n`;
    }

    if (config.returnsValue && config.returnFields) {
      ssaCode += `    return {\n`;
      for (const rf of config.returnFields) {
        ssaCode += `      ${rf.name}: data.${rf.name} || properties.${rf.name} || null,\n`;
      }
      ssaCode += `    };\n`;
    } else {
      ssaCode += `    return { success: true };\n`;
    }

    ssaCode += `  } catch (error) {\n    console.error("[${config.actionName}] Execution failure:", error.message);\n    throw error;\n  }\n}\n`;

    // 3. Generate Client-Side Action Code (CSA)
    let csaCode = `/**
 * Bubble Plugin Client-Side Action (CSA)
 * Action: ${config.actionName}
 * Paste into Bubble Plugin Editor > Actions > ${config.actionName} > Client-side code
 */

function(properties, context) {
  // Execute client-side JavaScript in the browser
  const eventName = "${actionNameClean.toLowerCase()}_event";
  
  try {
    const detail = {\n`;
    for (const p of config.parameters) {
      csaCode += `      ${p.name}: properties.${p.name},\n`;
    }
    csaCode += `    };\n\n`;
    csaCode += `    window.dispatchEvent(new CustomEvent(eventName, { detail }));\n`;
    csaCode += `    console.log("[Bubble Plugin] Dispatched client event:", eventName, detail);\n`;
    csaCode += `  } catch (err) {\n    console.error("[Bubble Plugin] Client action error:", err);\n  }\n}\n`;

    // 4. Package JSON snippet
    const packageJson = JSON.stringify({
      name: `bubble-plugin-${actionNameClean.toLowerCase()}`,
      version: '1.0.0',
      description: config.description || 'Bubble.io Plugin Action package',
      main: 'index.js',
      scripts: {
        build: 'tsc',
        test: 'jest'
      },
      dependencies: {
        axios: '^1.7.0',
        zod: '^3.23.8'
      },
      devDependencies: {
        typescript: '^5.5.0',
        '@types/node': '^20.0.0'
      }
    }, null, 2);

    return {
      serverSideCode: ssaCode,
      clientSideCode: csaCode,
      typeScriptInterfaces: tsInterfaces,
      packageJsonSnippet: packageJson
    };
  }
}
